[tool.poetry]
name = "renovate-poetry"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
